routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function() {
    Route::resource('roles','RoleController');
    Route::resource('users','UserController');
    Route::resource('leaves','LeaveController');

});

app/Leave.php
<?php
namespace App;

use Illuminate\Database\Eloquent\Model;

class Leave extends Model
{

    public function user()
    {
        return $this->belongsTo('App\User');
    }

    /**
     * The attributes that are mass assignable.
     *	
     * @var array
     */
    protected $fillable = [
        'vacation_start',
        'vacation_end',
        'reason',
        'status',
    ];
}

app/Http/Controllers/LeaveController.php
<?php

namespace App\Http\Controllers;

use App\Leave;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class LeaveController extends Controller
{ 
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:leave-list|leave-create|leave-edit|leave-delete', ['only' => ['index','show']]);
         $this->middleware('permission:leave-create', ['only' => ['create','store']]);
         $this->middleware('permission:leave-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:leave-delete', ['only' => ['destroy']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // BR 2 , BR 1
        if ( \Auth::user()->hasRole('Admin') ) $leaves = Leave::latest()->paginate(5);
        else if ( \Auth::user()->hasRole('Employee') ) $leaves = \Auth::user()->leaves()->paginate(5);
        else throw new Exception("Error Processing Request", 1);
        
        return view('leaves.index',compact('leaves'))
            ->with('i', (request()->input('page', 1) - 1) * 5);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('leaves.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        /**
            1. Date format
            2. Extra validation rule. must be later date.
        **/
        request()->validate([
            'vacation_start' => 'required|date',
            'vacation_end' => 'required|date|after:vacation_start',
            'reason' => 'required',
        ]);

        $leave = new Leave($request->all());
        \Auth::user()->leaves()->save($leave);

        return redirect()->route('leaves.index')
                        ->with('success','Leave created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Leave  $leave
     * @return \Illuminate\Http\Response
     */
    // public function show(Leave $leave)
    // {
    //     return view('leaves.show',compact('leave'));
    // }

    /**
     * Display the specified resource.
     *
     * @param  \App\Leave  $leave
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        return view('leaves.show',['leave' => Leave::findOrFail($id)]);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Leave  $leave
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        return view('leaves.edit',['leave' => Leave::findOrFail($id)]);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Leave  $leave
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate([
            'vacation_start' => 'required|date',
            'vacation_end' => 'required|date|after:vacation_start',
            'reason' => 'required',
            'status' => 'required|in:pending,approved,rejected'
        ]);

        $leave = Leave::findOrFail($id);
        $leave->update($request->all());
        return redirect()->route('leaves.index')
                        ->with('success','Leave updated successfully');
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Leave  $leave
     * @return \Illuminate\Http\Response
     */
    public function destroy(Leave $leave)
    {
        $leave->delete();
        return redirect()->route('leaves.index')
                        ->with('success','Leave deleted successfully');
    }
}

resources/views/leaves/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Submit Leave</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('leaves.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('leaves.store') }}" method="POST">
    	@csrf
         <div class="row">
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Start:</strong>
		            <input type="date" name="vacation_start" placeholder="dd/mm/yy">
                    <strong>End:</strong>
                    <input type="date" name="vacation_end" placeholder="dd/mm/yy">
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12">
		        <div class="form-group">
		            <strong>Reason:</strong>
		            <textarea class="form-control" style="height:150px" name="reason" placeholder="Type the why you request this leave."></textarea>
		        </div>
		    </div>
		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
		            <button type="submit" class="btn btn-primary">Submit</button>
		    </div>
		</div>
    </form>
<p class="text-center text-primary"><small>Epignosis</small></p>
@endsection

resources/views/leaves/edit.blade.php
@extends('layouts.app')
@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Edit Leave</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('leaves.index') }}"> Back</a>
            </div>
        </div>
    </div>

    @if ($errors->any())
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <form action="{{ route('leaves.update',$leave->id) }}" method="POST">
    	@csrf
        @method('PUT')

         <div class="row">
            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Start:</strong>
                    <input type="date" name="vacation_start" value="{{ $leave->vacation_start }}" placeholder="dd/mm/yy">
                    <strong>End:</strong>
                    <input type="date" name="vacation_end" value="{{ $leave->vacation_end }}" placeholder="dd/mm/yy">
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Status:</strong>
                    <select class="form-control" name="status">
                    @foreach (['pending','approved','rejected'] as $status)
                        <option value="{{ $status }}" {{ ( $status == $leave->status) ? 'selected' : '' }}> 
                            {{ $status }} 
                        </option>
                      @endforeach
                    </select> 
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12">
                <div class="form-group">
                    <strong>Reason:</strong>
                    <textarea readonly class="form-control" style="height:150px" name="reason">{{ $leave->reason }}</textarea>
                </div>
            </div>

		    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
		      <button type="submit" class="btn btn-primary">Submit</button>
		    </div>
		</div>

    </form>

<p class="text-center text-primary"><small>Epignosis</small></p>

@endsection

resources/views/leaves/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2>Leaves</h2>
            </div>
            <div class="pull-right">
                @can('leave-create')
                <a class="btn btn-success" href="{{ route('leaves.create') }}"> Submit Request</a>
                @endcan
            </div>
        </div>
    </div>

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    <table class="table table-bordered">
        <tr>
            <th>No</th>
            <th>Submitted</th>
            <th>Start</th>
            <th>End</th>
            <th>Status</th>
            <th width="280px">Action</th>
        </tr>
	    @foreach ($leaves as $leave)
	    <tr>
	        <td>{{ ++$i }}</td>
	        <td>{{ $leave->submit }}</td>
	        <td>{{ $leave->vacation_start }}</td>
            <td>{{ $leave->vacation_end }}</td>
            <td>{{ $leave->status }}</td>   
	        <td>
                <form action="{{ route('leaves.destroy',$leave->id) }}" method="POST">
                    <a class="btn btn-info" href="{{ route('leaves.show',$leave->id) }}">Show</a>
                    @can('leave-edit')
                    <a class="btn btn-primary" href="{{ route('leaves.edit',$leave->id) }}">Edit</a>
                    @endcan

                    @csrf
                    @method('DELETE')
                    @can('leave-delete')
                    <button type="submit" class="btn btn-danger">Delete</button>
                    @endcan
                </form>
	        </td>
	    </tr>
	    @endforeach
    </table>

    {!! $leaves->links() !!}

<p class="text-center text-primary"><small>Epignosis</small></p>
@endsection

resources/views/leaves/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2> Show Leave</h2>
            </div>
            <div class="pull-right">
                <a class="btn btn-primary" href="{{ route('leaves.index') }}"> Back</a>
            </div>
        </div>
    </div>

     <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Start:</strong>
                <input readonly type="date" name="vacation_start" value="{{ $leave->vacation_start }}" placeholder="dd/mm/yy">
                <strong>End:</strong>
                <input readonly type="date" name="vacation_end" value="{{ $leave->vacation_end }}" placeholder="dd/mm/yy">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Status:</strong> {{ $leave->status }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Reason:</strong>
                <textarea readonly class="form-control" style="height:150px" name="reason">{{ $leave->reason }}</textarea>
            </div>
        </div>
    </div>

@endsection

<p class="text-center text-primary"><small>Epignosis</small></p>